/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthenticatedSetupGuideRouteImport } from './routes/_authenticated/setup-guide'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoundsRouteImport } from './routes/_authenticated/rounds'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPoolsRouteImport } from './routes/_authenticated/pools'
import { Route as AuthenticatedMetaApiRouteImport } from './routes/_authenticated/meta-api'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedImportReceiverRouteImport } from './routes/_authenticated/import-receiver'
import { Route as AuthenticatedImportCenterRouteImport } from './routes/_authenticated/import-center'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as AuthenticatedCloneAccountRouteImport } from './routes/_authenticated/clone-account'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram/callback'
import { Route as ApiPublicCronReapStuckRouteImport } from './routes/api/public/cron/reap-stuck'
import { Route as ApiPublicCronPublishScheduledRouteImport } from './routes/api/public/cron/publish-scheduled'
import { Route as ApiPublicCronProcessPoolsRouteImport } from './routes/api/public/cron/process-pools'
import { Route as ApiPublicCronMonitorPostsRouteImport } from './routes/api/public/cron/monitor-posts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupGuideRoute = AuthenticatedSetupGuideRouteImport.update({
  id: '/setup-guide',
  path: '/setup-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoundsRoute = AuthenticatedRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoolsRoute = AuthenticatedPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetaApiRoute = AuthenticatedMetaApiRouteImport.update({
  id: '/meta-api',
  path: '/meta-api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportReceiverRoute =
  AuthenticatedImportReceiverRouteImport.update({
    id: '/import-receiver',
    path: '/import-receiver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportCenterRoute =
  AuthenticatedImportCenterRouteImport.update({
    id: '/import-center',
    path: '/import-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCloneAccountRoute =
  AuthenticatedCloneAccountRouteImport.update({
    id: '/clone-account',
    path: '/clone-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReapStuckRoute = ApiPublicCronReapStuckRouteImport.update({
  id: '/api/public/cron/reap-stuck',
  path: '/api/public/cron/reap-stuck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPublishScheduledRoute =
  ApiPublicCronPublishScheduledRouteImport.update({
    id: '/api/public/cron/publish-scheduled',
    path: '/api/public/cron/publish-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronProcessPoolsRoute =
  ApiPublicCronProcessPoolsRouteImport.update({
    id: '/api/public/cron/process-pools',
    path: '/api/public/cron/process-pools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMonitorPostsRoute =
  ApiPublicCronMonitorPostsRouteImport.update({
    id: '/api/public/cron/monitor-posts',
    path: '/api/public/cron/monitor-posts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clone-account': typeof AuthenticatedCloneAccountRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-center': typeof AuthenticatedImportCenterRoute
  '/import-receiver': typeof AuthenticatedImportReceiverRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/media': typeof AuthenticatedMediaRoute
  '/meta-api': typeof AuthenticatedMetaApiRoute
  '/pools': typeof AuthenticatedPoolsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/rounds': typeof AuthenticatedRoundsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup-guide': typeof AuthenticatedSetupGuideRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/cron/monitor-posts': typeof ApiPublicCronMonitorPostsRoute
  '/api/public/cron/process-pools': typeof ApiPublicCronProcessPoolsRoute
  '/api/public/cron/publish-scheduled': typeof ApiPublicCronPublishScheduledRoute
  '/api/public/cron/reap-stuck': typeof ApiPublicCronReapStuckRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clone-account': typeof AuthenticatedCloneAccountRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-center': typeof AuthenticatedImportCenterRoute
  '/import-receiver': typeof AuthenticatedImportReceiverRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/media': typeof AuthenticatedMediaRoute
  '/meta-api': typeof AuthenticatedMetaApiRoute
  '/pools': typeof AuthenticatedPoolsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/rounds': typeof AuthenticatedRoundsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup-guide': typeof AuthenticatedSetupGuideRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/cron/monitor-posts': typeof ApiPublicCronMonitorPostsRoute
  '/api/public/cron/process-pools': typeof ApiPublicCronProcessPoolsRoute
  '/api/public/cron/publish-scheduled': typeof ApiPublicCronPublishScheduledRoute
  '/api/public/cron/reap-stuck': typeof ApiPublicCronReapStuckRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clone-account': typeof AuthenticatedCloneAccountRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-center': typeof AuthenticatedImportCenterRoute
  '/_authenticated/import-receiver': typeof AuthenticatedImportReceiverRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/meta-api': typeof AuthenticatedMetaApiRoute
  '/_authenticated/pools': typeof AuthenticatedPoolsRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/rounds': typeof AuthenticatedRoundsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup-guide': typeof AuthenticatedSetupGuideRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/cron/monitor-posts': typeof ApiPublicCronMonitorPostsRoute
  '/api/public/cron/process-pools': typeof ApiPublicCronProcessPoolsRoute
  '/api/public/cron/publish-scheduled': typeof ApiPublicCronPublishScheduledRoute
  '/api/public/cron/reap-stuck': typeof ApiPublicCronReapStuckRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/clone-account'
    | '/compose'
    | '/dashboard'
    | '/import-center'
    | '/import-receiver'
    | '/invites'
    | '/media'
    | '/meta-api'
    | '/pools'
    | '/queue'
    | '/rounds'
    | '/settings'
    | '/setup-guide'
    | '/api/tts'
    | '/api/public/cron/monitor-posts'
    | '/api/public/cron/process-pools'
    | '/api/public/cron/publish-scheduled'
    | '/api/public/cron/reap-stuck'
    | '/api/public/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/calendar'
    | '/clone-account'
    | '/compose'
    | '/dashboard'
    | '/import-center'
    | '/import-receiver'
    | '/invites'
    | '/media'
    | '/meta-api'
    | '/pools'
    | '/queue'
    | '/rounds'
    | '/settings'
    | '/setup-guide'
    | '/api/tts'
    | '/api/public/cron/monitor-posts'
    | '/api/public/cron/process-pools'
    | '/api/public/cron/publish-scheduled'
    | '/api/public/cron/reap-stuck'
    | '/api/public/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/clone-account'
    | '/_authenticated/compose'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-center'
    | '/_authenticated/import-receiver'
    | '/_authenticated/invites'
    | '/_authenticated/media'
    | '/_authenticated/meta-api'
    | '/_authenticated/pools'
    | '/_authenticated/queue'
    | '/_authenticated/rounds'
    | '/_authenticated/settings'
    | '/_authenticated/setup-guide'
    | '/api/tts'
    | '/api/public/cron/monitor-posts'
    | '/api/public/cron/process-pools'
    | '/api/public/cron/publish-scheduled'
    | '/api/public/cron/reap-stuck'
    | '/api/public/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicCronMonitorPostsRoute: typeof ApiPublicCronMonitorPostsRoute
  ApiPublicCronProcessPoolsRoute: typeof ApiPublicCronProcessPoolsRoute
  ApiPublicCronPublishScheduledRoute: typeof ApiPublicCronPublishScheduledRoute
  ApiPublicCronReapStuckRoute: typeof ApiPublicCronReapStuckRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup-guide': {
      id: '/_authenticated/setup-guide'
      path: '/setup-guide'
      fullPath: '/setup-guide'
      preLoaderRoute: typeof AuthenticatedSetupGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rounds': {
      id: '/_authenticated/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof AuthenticatedRoundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pools': {
      id: '/_authenticated/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof AuthenticatedPoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-api': {
      id: '/_authenticated/meta-api'
      path: '/meta-api'
      fullPath: '/meta-api'
      preLoaderRoute: typeof AuthenticatedMetaApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-receiver': {
      id: '/_authenticated/import-receiver'
      path: '/import-receiver'
      fullPath: '/import-receiver'
      preLoaderRoute: typeof AuthenticatedImportReceiverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-center': {
      id: '/_authenticated/import-center'
      path: '/import-center'
      fullPath: '/import-center'
      preLoaderRoute: typeof AuthenticatedImportCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clone-account': {
      id: '/_authenticated/clone-account'
      path: '/clone-account'
      fullPath: '/clone-account'
      preLoaderRoute: typeof AuthenticatedCloneAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reap-stuck': {
      id: '/api/public/cron/reap-stuck'
      path: '/api/public/cron/reap-stuck'
      fullPath: '/api/public/cron/reap-stuck'
      preLoaderRoute: typeof ApiPublicCronReapStuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/publish-scheduled': {
      id: '/api/public/cron/publish-scheduled'
      path: '/api/public/cron/publish-scheduled'
      fullPath: '/api/public/cron/publish-scheduled'
      preLoaderRoute: typeof ApiPublicCronPublishScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-pools': {
      id: '/api/public/cron/process-pools'
      path: '/api/public/cron/process-pools'
      fullPath: '/api/public/cron/process-pools'
      preLoaderRoute: typeof ApiPublicCronProcessPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monitor-posts': {
      id: '/api/public/cron/monitor-posts'
      path: '/api/public/cron/monitor-posts'
      fullPath: '/api/public/cron/monitor-posts'
      preLoaderRoute: typeof ApiPublicCronMonitorPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCloneAccountRoute: typeof AuthenticatedCloneAccountRoute
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportCenterRoute: typeof AuthenticatedImportCenterRoute
  AuthenticatedImportReceiverRoute: typeof AuthenticatedImportReceiverRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedMetaApiRoute: typeof AuthenticatedMetaApiRoute
  AuthenticatedPoolsRoute: typeof AuthenticatedPoolsRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRoundsRoute: typeof AuthenticatedRoundsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupGuideRoute: typeof AuthenticatedSetupGuideRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCloneAccountRoute: AuthenticatedCloneAccountRoute,
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportCenterRoute: AuthenticatedImportCenterRoute,
  AuthenticatedImportReceiverRoute: AuthenticatedImportReceiverRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedMetaApiRoute: AuthenticatedMetaApiRoute,
  AuthenticatedPoolsRoute: AuthenticatedPoolsRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRoundsRoute: AuthenticatedRoundsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupGuideRoute: AuthenticatedSetupGuideRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicCronMonitorPostsRoute: ApiPublicCronMonitorPostsRoute,
  ApiPublicCronProcessPoolsRoute: ApiPublicCronProcessPoolsRoute,
  ApiPublicCronPublishScheduledRoute: ApiPublicCronPublishScheduledRoute,
  ApiPublicCronReapStuckRoute: ApiPublicCronReapStuckRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
